name: RSS to README
description: Replaces a section of the repo's README with the contents of an RSS feed
inputs:
  source-url:
    default: 'https://www.brvm.org/en/cours-actions/0'
    required: true
    description: A URL to an html page.
  github_token:
    default: ${{ github.token }}
  branch:
    default: ${{ github.event.repository.default_branch }}
    description: The target branch to update.
  empty-commits:
    default: 'true'
    description: set to `false` to disallow empty commits when there are no changes
runs:
  using: node12
  main: dist/index.js
branding:
  icon: activity
  color: red